// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.1
// source: phobos.cloak.power.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export interface GetPhasePower {
}

export interface GetPhasePower_Request {
}

export interface GetPhasePower_Response {
  power: number[];
}

export interface SetPhasePower {
}

export interface SetPhasePower_Request {
  power: number[];
}

export interface SetPhasePower_Response {
}

export interface GetTargetPhasePower {
}

export interface GetTargetPhasePower_Request {
}

export interface GetTargetPhasePower_Response {
  power: number[];
}

export interface SetTargetPhasePower {
}

export interface SetTargetPhasePower_Request {
  power: number[];
}

export interface SetTargetPhasePower_Response {
}

function createBaseGetPhasePower(): GetPhasePower {
  return {};
}

export const GetPhasePower = {
  encode(_: GetPhasePower, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetPhasePower {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPhasePower();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetPhasePower {
    return {};
  },

  toJSON(_: GetPhasePower): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPhasePower>, I>>(base?: I): GetPhasePower {
    return GetPhasePower.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPhasePower>, I>>(_: I): GetPhasePower {
    const message = createBaseGetPhasePower();
    return message;
  },
};

function createBaseGetPhasePower_Request(): GetPhasePower_Request {
  return {};
}

export const GetPhasePower_Request = {
  encode(_: GetPhasePower_Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetPhasePower_Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPhasePower_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetPhasePower_Request {
    return {};
  },

  toJSON(_: GetPhasePower_Request): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPhasePower_Request>, I>>(base?: I): GetPhasePower_Request {
    return GetPhasePower_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPhasePower_Request>, I>>(_: I): GetPhasePower_Request {
    const message = createBaseGetPhasePower_Request();
    return message;
  },
};

function createBaseGetPhasePower_Response(): GetPhasePower_Response {
  return { power: [] };
}

export const GetPhasePower_Response = {
  encode(message: GetPhasePower_Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.power) {
      writer.int32(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetPhasePower_Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPhasePower_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 8) {
            message.power.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.power.push(reader.int32());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPhasePower_Response {
    return { power: globalThis.Array.isArray(object?.power) ? object.power.map((e: any) => globalThis.Number(e)) : [] };
  },

  toJSON(message: GetPhasePower_Response): unknown {
    const obj: any = {};
    if (message.power?.length) {
      obj.power = message.power.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPhasePower_Response>, I>>(base?: I): GetPhasePower_Response {
    return GetPhasePower_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPhasePower_Response>, I>>(object: I): GetPhasePower_Response {
    const message = createBaseGetPhasePower_Response();
    message.power = object.power?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetPhasePower(): SetPhasePower {
  return {};
}

export const SetPhasePower = {
  encode(_: SetPhasePower, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetPhasePower {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetPhasePower();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetPhasePower {
    return {};
  },

  toJSON(_: SetPhasePower): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetPhasePower>, I>>(base?: I): SetPhasePower {
    return SetPhasePower.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetPhasePower>, I>>(_: I): SetPhasePower {
    const message = createBaseSetPhasePower();
    return message;
  },
};

function createBaseSetPhasePower_Request(): SetPhasePower_Request {
  return { power: [] };
}

export const SetPhasePower_Request = {
  encode(message: SetPhasePower_Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.power) {
      writer.int32(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetPhasePower_Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetPhasePower_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 8) {
            message.power.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.power.push(reader.int32());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetPhasePower_Request {
    return { power: globalThis.Array.isArray(object?.power) ? object.power.map((e: any) => globalThis.Number(e)) : [] };
  },

  toJSON(message: SetPhasePower_Request): unknown {
    const obj: any = {};
    if (message.power?.length) {
      obj.power = message.power.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetPhasePower_Request>, I>>(base?: I): SetPhasePower_Request {
    return SetPhasePower_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetPhasePower_Request>, I>>(object: I): SetPhasePower_Request {
    const message = createBaseSetPhasePower_Request();
    message.power = object.power?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetPhasePower_Response(): SetPhasePower_Response {
  return {};
}

export const SetPhasePower_Response = {
  encode(_: SetPhasePower_Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetPhasePower_Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetPhasePower_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetPhasePower_Response {
    return {};
  },

  toJSON(_: SetPhasePower_Response): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetPhasePower_Response>, I>>(base?: I): SetPhasePower_Response {
    return SetPhasePower_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetPhasePower_Response>, I>>(_: I): SetPhasePower_Response {
    const message = createBaseSetPhasePower_Response();
    return message;
  },
};

function createBaseGetTargetPhasePower(): GetTargetPhasePower {
  return {};
}

export const GetTargetPhasePower = {
  encode(_: GetTargetPhasePower, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetTargetPhasePower {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTargetPhasePower();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetTargetPhasePower {
    return {};
  },

  toJSON(_: GetTargetPhasePower): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTargetPhasePower>, I>>(base?: I): GetTargetPhasePower {
    return GetTargetPhasePower.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTargetPhasePower>, I>>(_: I): GetTargetPhasePower {
    const message = createBaseGetTargetPhasePower();
    return message;
  },
};

function createBaseGetTargetPhasePower_Request(): GetTargetPhasePower_Request {
  return {};
}

export const GetTargetPhasePower_Request = {
  encode(_: GetTargetPhasePower_Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetTargetPhasePower_Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTargetPhasePower_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetTargetPhasePower_Request {
    return {};
  },

  toJSON(_: GetTargetPhasePower_Request): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTargetPhasePower_Request>, I>>(base?: I): GetTargetPhasePower_Request {
    return GetTargetPhasePower_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTargetPhasePower_Request>, I>>(_: I): GetTargetPhasePower_Request {
    const message = createBaseGetTargetPhasePower_Request();
    return message;
  },
};

function createBaseGetTargetPhasePower_Response(): GetTargetPhasePower_Response {
  return { power: [] };
}

export const GetTargetPhasePower_Response = {
  encode(message: GetTargetPhasePower_Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.power) {
      writer.float(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetTargetPhasePower_Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTargetPhasePower_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 13) {
            message.power.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.power.push(reader.float());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTargetPhasePower_Response {
    return { power: globalThis.Array.isArray(object?.power) ? object.power.map((e: any) => globalThis.Number(e)) : [] };
  },

  toJSON(message: GetTargetPhasePower_Response): unknown {
    const obj: any = {};
    if (message.power?.length) {
      obj.power = message.power;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTargetPhasePower_Response>, I>>(base?: I): GetTargetPhasePower_Response {
    return GetTargetPhasePower_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTargetPhasePower_Response>, I>>(object: I): GetTargetPhasePower_Response {
    const message = createBaseGetTargetPhasePower_Response();
    message.power = object.power?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetTargetPhasePower(): SetTargetPhasePower {
  return {};
}

export const SetTargetPhasePower = {
  encode(_: SetTargetPhasePower, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetTargetPhasePower {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTargetPhasePower();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetTargetPhasePower {
    return {};
  },

  toJSON(_: SetTargetPhasePower): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTargetPhasePower>, I>>(base?: I): SetTargetPhasePower {
    return SetTargetPhasePower.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTargetPhasePower>, I>>(_: I): SetTargetPhasePower {
    const message = createBaseSetTargetPhasePower();
    return message;
  },
};

function createBaseSetTargetPhasePower_Request(): SetTargetPhasePower_Request {
  return { power: [] };
}

export const SetTargetPhasePower_Request = {
  encode(message: SetTargetPhasePower_Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.power) {
      writer.float(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetTargetPhasePower_Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTargetPhasePower_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 13) {
            message.power.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.power.push(reader.float());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetTargetPhasePower_Request {
    return { power: globalThis.Array.isArray(object?.power) ? object.power.map((e: any) => globalThis.Number(e)) : [] };
  },

  toJSON(message: SetTargetPhasePower_Request): unknown {
    const obj: any = {};
    if (message.power?.length) {
      obj.power = message.power;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTargetPhasePower_Request>, I>>(base?: I): SetTargetPhasePower_Request {
    return SetTargetPhasePower_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTargetPhasePower_Request>, I>>(object: I): SetTargetPhasePower_Request {
    const message = createBaseSetTargetPhasePower_Request();
    message.power = object.power?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetTargetPhasePower_Response(): SetTargetPhasePower_Response {
  return {};
}

export const SetTargetPhasePower_Response = {
  encode(_: SetTargetPhasePower_Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetTargetPhasePower_Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTargetPhasePower_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetTargetPhasePower_Response {
    return {};
  },

  toJSON(_: SetTargetPhasePower_Response): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTargetPhasePower_Response>, I>>(base?: I): SetTargetPhasePower_Response {
    return SetTargetPhasePower_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTargetPhasePower_Response>, I>>(_: I): SetTargetPhasePower_Response {
    const message = createBaseSetTargetPhasePower_Response();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };
