// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.24.2
// source: phobos.cloak.cluster.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export interface SetClusterMixingMatrix {
}

export interface SetClusterMixingMatrix_Request {
  matrix: number[];
}

export interface SetClusterMixingMatrix_Response {
}

export interface GetClusterMixingMatrix {
}

export interface GetClusterMixingMatrix_Request {
}

export interface GetClusterMixingMatrix_Response {
  matrix: number[];
}

export interface GetTargetClusterMixingMatrix {
}

export interface GetTargetClusterMixingMatrix_Request {
}

export interface GetTargetClusterMixingMatrix_Response {
  matrix: number[];
}

export interface SetTargetClusterMixingMatrix {
}

export interface SetTargetClusterMixingMatrix_Request {
  matrix: number[];
}

export interface SetTargetClusterMixingMatrix_Response {
}

function createBaseSetClusterMixingMatrix(): SetClusterMixingMatrix {
  return {};
}

export const SetClusterMixingMatrix = {
  encode(_: SetClusterMixingMatrix, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetClusterMixingMatrix {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetClusterMixingMatrix();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetClusterMixingMatrix {
    return {};
  },

  toJSON(_: SetClusterMixingMatrix): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetClusterMixingMatrix>, I>>(base?: I): SetClusterMixingMatrix {
    return SetClusterMixingMatrix.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetClusterMixingMatrix>, I>>(_: I): SetClusterMixingMatrix {
    const message = createBaseSetClusterMixingMatrix();
    return message;
  },
};

function createBaseSetClusterMixingMatrix_Request(): SetClusterMixingMatrix_Request {
  return { matrix: [] };
}

export const SetClusterMixingMatrix_Request = {
  encode(message: SetClusterMixingMatrix_Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.matrix) {
      writer.float(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetClusterMixingMatrix_Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetClusterMixingMatrix_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 13) {
            message.matrix.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.matrix.push(reader.float());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetClusterMixingMatrix_Request {
    return {
      matrix: globalThis.Array.isArray(object?.matrix) ? object.matrix.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: SetClusterMixingMatrix_Request): unknown {
    const obj: any = {};
    if (message.matrix?.length) {
      obj.matrix = message.matrix;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetClusterMixingMatrix_Request>, I>>(base?: I): SetClusterMixingMatrix_Request {
    return SetClusterMixingMatrix_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetClusterMixingMatrix_Request>, I>>(
    object: I,
  ): SetClusterMixingMatrix_Request {
    const message = createBaseSetClusterMixingMatrix_Request();
    message.matrix = object.matrix?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetClusterMixingMatrix_Response(): SetClusterMixingMatrix_Response {
  return {};
}

export const SetClusterMixingMatrix_Response = {
  encode(_: SetClusterMixingMatrix_Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetClusterMixingMatrix_Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetClusterMixingMatrix_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetClusterMixingMatrix_Response {
    return {};
  },

  toJSON(_: SetClusterMixingMatrix_Response): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetClusterMixingMatrix_Response>, I>>(base?: I): SetClusterMixingMatrix_Response {
    return SetClusterMixingMatrix_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetClusterMixingMatrix_Response>, I>>(_: I): SetClusterMixingMatrix_Response {
    const message = createBaseSetClusterMixingMatrix_Response();
    return message;
  },
};

function createBaseGetClusterMixingMatrix(): GetClusterMixingMatrix {
  return {};
}

export const GetClusterMixingMatrix = {
  encode(_: GetClusterMixingMatrix, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetClusterMixingMatrix {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetClusterMixingMatrix();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetClusterMixingMatrix {
    return {};
  },

  toJSON(_: GetClusterMixingMatrix): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetClusterMixingMatrix>, I>>(base?: I): GetClusterMixingMatrix {
    return GetClusterMixingMatrix.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetClusterMixingMatrix>, I>>(_: I): GetClusterMixingMatrix {
    const message = createBaseGetClusterMixingMatrix();
    return message;
  },
};

function createBaseGetClusterMixingMatrix_Request(): GetClusterMixingMatrix_Request {
  return {};
}

export const GetClusterMixingMatrix_Request = {
  encode(_: GetClusterMixingMatrix_Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetClusterMixingMatrix_Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetClusterMixingMatrix_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetClusterMixingMatrix_Request {
    return {};
  },

  toJSON(_: GetClusterMixingMatrix_Request): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetClusterMixingMatrix_Request>, I>>(base?: I): GetClusterMixingMatrix_Request {
    return GetClusterMixingMatrix_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetClusterMixingMatrix_Request>, I>>(_: I): GetClusterMixingMatrix_Request {
    const message = createBaseGetClusterMixingMatrix_Request();
    return message;
  },
};

function createBaseGetClusterMixingMatrix_Response(): GetClusterMixingMatrix_Response {
  return { matrix: [] };
}

export const GetClusterMixingMatrix_Response = {
  encode(message: GetClusterMixingMatrix_Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.matrix) {
      writer.float(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetClusterMixingMatrix_Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetClusterMixingMatrix_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 13) {
            message.matrix.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.matrix.push(reader.float());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetClusterMixingMatrix_Response {
    return {
      matrix: globalThis.Array.isArray(object?.matrix) ? object.matrix.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: GetClusterMixingMatrix_Response): unknown {
    const obj: any = {};
    if (message.matrix?.length) {
      obj.matrix = message.matrix;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetClusterMixingMatrix_Response>, I>>(base?: I): GetClusterMixingMatrix_Response {
    return GetClusterMixingMatrix_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetClusterMixingMatrix_Response>, I>>(
    object: I,
  ): GetClusterMixingMatrix_Response {
    const message = createBaseGetClusterMixingMatrix_Response();
    message.matrix = object.matrix?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetTargetClusterMixingMatrix(): GetTargetClusterMixingMatrix {
  return {};
}

export const GetTargetClusterMixingMatrix = {
  encode(_: GetTargetClusterMixingMatrix, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetTargetClusterMixingMatrix {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTargetClusterMixingMatrix();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetTargetClusterMixingMatrix {
    return {};
  },

  toJSON(_: GetTargetClusterMixingMatrix): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTargetClusterMixingMatrix>, I>>(base?: I): GetTargetClusterMixingMatrix {
    return GetTargetClusterMixingMatrix.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTargetClusterMixingMatrix>, I>>(_: I): GetTargetClusterMixingMatrix {
    const message = createBaseGetTargetClusterMixingMatrix();
    return message;
  },
};

function createBaseGetTargetClusterMixingMatrix_Request(): GetTargetClusterMixingMatrix_Request {
  return {};
}

export const GetTargetClusterMixingMatrix_Request = {
  encode(_: GetTargetClusterMixingMatrix_Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetTargetClusterMixingMatrix_Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTargetClusterMixingMatrix_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetTargetClusterMixingMatrix_Request {
    return {};
  },

  toJSON(_: GetTargetClusterMixingMatrix_Request): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTargetClusterMixingMatrix_Request>, I>>(
    base?: I,
  ): GetTargetClusterMixingMatrix_Request {
    return GetTargetClusterMixingMatrix_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTargetClusterMixingMatrix_Request>, I>>(
    _: I,
  ): GetTargetClusterMixingMatrix_Request {
    const message = createBaseGetTargetClusterMixingMatrix_Request();
    return message;
  },
};

function createBaseGetTargetClusterMixingMatrix_Response(): GetTargetClusterMixingMatrix_Response {
  return { matrix: [] };
}

export const GetTargetClusterMixingMatrix_Response = {
  encode(message: GetTargetClusterMixingMatrix_Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.matrix) {
      writer.float(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetTargetClusterMixingMatrix_Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTargetClusterMixingMatrix_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 13) {
            message.matrix.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.matrix.push(reader.float());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTargetClusterMixingMatrix_Response {
    return {
      matrix: globalThis.Array.isArray(object?.matrix) ? object.matrix.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: GetTargetClusterMixingMatrix_Response): unknown {
    const obj: any = {};
    if (message.matrix?.length) {
      obj.matrix = message.matrix;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTargetClusterMixingMatrix_Response>, I>>(
    base?: I,
  ): GetTargetClusterMixingMatrix_Response {
    return GetTargetClusterMixingMatrix_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTargetClusterMixingMatrix_Response>, I>>(
    object: I,
  ): GetTargetClusterMixingMatrix_Response {
    const message = createBaseGetTargetClusterMixingMatrix_Response();
    message.matrix = object.matrix?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetTargetClusterMixingMatrix(): SetTargetClusterMixingMatrix {
  return {};
}

export const SetTargetClusterMixingMatrix = {
  encode(_: SetTargetClusterMixingMatrix, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetTargetClusterMixingMatrix {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTargetClusterMixingMatrix();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetTargetClusterMixingMatrix {
    return {};
  },

  toJSON(_: SetTargetClusterMixingMatrix): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTargetClusterMixingMatrix>, I>>(base?: I): SetTargetClusterMixingMatrix {
    return SetTargetClusterMixingMatrix.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTargetClusterMixingMatrix>, I>>(_: I): SetTargetClusterMixingMatrix {
    const message = createBaseSetTargetClusterMixingMatrix();
    return message;
  },
};

function createBaseSetTargetClusterMixingMatrix_Request(): SetTargetClusterMixingMatrix_Request {
  return { matrix: [] };
}

export const SetTargetClusterMixingMatrix_Request = {
  encode(message: SetTargetClusterMixingMatrix_Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.matrix) {
      writer.float(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetTargetClusterMixingMatrix_Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTargetClusterMixingMatrix_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 13) {
            message.matrix.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.matrix.push(reader.float());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetTargetClusterMixingMatrix_Request {
    return {
      matrix: globalThis.Array.isArray(object?.matrix) ? object.matrix.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: SetTargetClusterMixingMatrix_Request): unknown {
    const obj: any = {};
    if (message.matrix?.length) {
      obj.matrix = message.matrix;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTargetClusterMixingMatrix_Request>, I>>(
    base?: I,
  ): SetTargetClusterMixingMatrix_Request {
    return SetTargetClusterMixingMatrix_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTargetClusterMixingMatrix_Request>, I>>(
    object: I,
  ): SetTargetClusterMixingMatrix_Request {
    const message = createBaseSetTargetClusterMixingMatrix_Request();
    message.matrix = object.matrix?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetTargetClusterMixingMatrix_Response(): SetTargetClusterMixingMatrix_Response {
  return {};
}

export const SetTargetClusterMixingMatrix_Response = {
  encode(_: SetTargetClusterMixingMatrix_Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetTargetClusterMixingMatrix_Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTargetClusterMixingMatrix_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetTargetClusterMixingMatrix_Response {
    return {};
  },

  toJSON(_: SetTargetClusterMixingMatrix_Response): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTargetClusterMixingMatrix_Response>, I>>(
    base?: I,
  ): SetTargetClusterMixingMatrix_Response {
    return SetTargetClusterMixingMatrix_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTargetClusterMixingMatrix_Response>, I>>(
    _: I,
  ): SetTargetClusterMixingMatrix_Response {
    const message = createBaseSetTargetClusterMixingMatrix_Response();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };
