apiVersion: v1
kind: Service
metadata:
  name: phobos-cloak-service
  labels:
    type: mfe
    name: phobos-cloak
spec:
  selector:
    app: phobos-cloak
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4006
